# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: hello

resources:
- namespace.yaml
- ingress.yaml
- deployment.yaml
- service.yaml
- configMap.yaml

namespace: example